version: '3.2'

services:

  radsecproxy:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./configs/radsecproxy/radsecproxy.conf:/etc/radsecproxy.conf"
      - "./configs/radsecproxy/certs:/etc/radsecproxy/certs"
    environment:
      - RUN_IN_BACKGROUND=false
    restart: always
    ports:
      - "11812:11812/tcp"
      - "11812:11812/udp"
      - "11813:11813/tcp"
      - "11813:11813/udp"
      - "2083:2083/udp"
      - "2083:2083/tcp"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: radius
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./configs/mysql/schema/freeradius.sql:/docker-entrypoint-initdb.d/freeradius.sql

  freeradius:
    restart: always
    build:
      dockerfile: DockerfileFreeRadius
      context: .
    command: [ "radiusd", "-f", "-l", "/dev/stdout", "-xx" ]
    depends_on:
      - radsecproxy
      - mysql
    volumes:
      - ./configs/freeradius/mods-available/sql:/etc/freeradius/mods-enabled/sql
      - ./configs/freeradius/mods-available/eap:/etc/freeradius/mods-enabled/eap
volumes:
  mysql_data:
