version: '3.2'

services:

  radsecproxy:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./configs/radsecproxy/radsecproxy.conf:/etc/radsecproxy.conf"
      - "./configs/radsecproxy/certs:/etc/radsecproxy/certs"

    environment:
      - RUN_IN_BACKGROUND=false
    restart: always
    ports:
      - "2083:2083"

  freeradius:
    build:
      dockerfile: DockerfileFreeRadius
      context: .
    command: ["radiusd", "-f", "-l", "/dev/stdout", "-xx"]
    depends_on:
      - radsecproxy
    volumes:
      - ./configs/freeradius/mods-config/files/authorize:/etc/freeradius/mods-config/files/authorize
#    command:
#      - -X
    ports:
      - "1812:1812"
      - "1813:1813"
